service: starwars

useDotenv: true


provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-1
  profile: jcastrov
  timeout: 15
  environment:
    JWT_SECRET: ${env:JWT_SECRET}
    JWT_EXPIRATION_TIME: ${env:JWT_EXPIRES_IN}
    DB_HOST: ${env:DB_HOST}
    DB_PORT: ${env:DB_PORT}
    DB_USERNAME: ${env:DB_USERNAME}
    DB_DATABASE: ${env:DB_DATABASE}

functions:
  main:
    handler: dist/lambda.handler
    maximumEventAge: 300
    maximumRetryAttempts: 2
    timeout: 300
    package:
      include:
        - dist/**
      exclude:
        - tests/**
        - .vscode/**
        - .env
        - README.md
        - "*.log"
    events:
      - httpApi:
          method: any
          path: /{proxy+}

plugins:
  - serverless-offline
  - serverless-jetpack


